name: Line Count Check

on: [push, pull_request]

jobs:
  lines:
    name: Check lines of code (need <= 2000 lines)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install SLOCCount
      run: sudo apt install sloccount
    - name: Check <= 2500 lines
      run: sloccount froog tests examples models docs; if [ $(sloccount test froog | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 2500 ]; then exit 1; fi
