name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    name: Tensor Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Pytest 
      run: python -m pytest -s -v
    - name: Run EfficientNet model
      run: |
        export PYTHONPATH=$GITHUB_WORKSPACE
        python3 models/efficientnet.py > model_output.txt
        if ! grep -q "pug" model_output.txt; then
          echo "Error: 'pug' not found in model output"
          exit 1
        fi