name: Unit Tests

on: [push, pull_request]

jobs:
  lines:
    name: Check lines of code (need <= 2000 lines)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install SLOCCount
      run: sudo apt install sloccount
    - name: Check <= 2000 lines
      run: sloccount froog tests examples models docs; if [ $(sloccount test froog | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 2000 ]; then exit 1; fi

  test:
    name: Tensor Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Pytest 
      run: python -m pytest -s -v
    - name: Run EfficientNet model with args
      run: python3 models/efficientnet.py